name: Build and deploy Spotify-GPT-Bot Python app to Azure Web App

env:
  AZURE_WEBAPP_NAME: Spotify-GPT-Bot 
  WORKING_DIRECTORY: '.' 
  PYTHON_VERSION: '3.9' 
  STARTUP_COMMAND: 'gunicorn -w 2 -k uvicorn.workers.UvicornWorker webapp.main:app'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
 build-and-deploy:
  runs-on: ubuntu-latest
  environment: dev
  steps:
  # checkout the repo 
  - uses: actions/checkout@master
  # setup python
  - name: Setup Python
    uses: actions/setup-python@v1
    with:
     python-version: ${{ env.PYTHON_VERSION }}
  # install dependencies
  - name: python install
    working-directory: ${{ env.WORKING_DIRECTORY }}
    run: |
     sudo apt install python${{ env.PYTHON_VERSION }}-venv
     python -m venv --copies antenv
     source antenv/bin/activate
     pip install setuptools
     pip install -r requirements.txt
  # Azure login
  - uses: azure/login@v1
    with:
     creds: ${{ secrets.AZURE_CREDENTIALS }}
  
  - name: Set OpenAI key
    run: echo "OPENAI_KEY=${{ secrets.OPENAI_KEY }}" >> $GITHUB_ENV
      
  - uses: azure/appservice-settings@v1  
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     mask-inputs: false
     general-settings-json: '{"linuxFxVersion": "PYTHON|${{ env.PYTHON_VERSION }}"}' #'General configuration settings as Key Value pairs'
     app-settings-json: '{"OPENAI_API_KEY": "${{ secrets.OPENAI_API_KEY }}", "SPOTIFY_CLIENT_ID": "${{ secrets.SPOTIFY_CLIENT_ID }}", "SPOTIFY_CLIENT_SECRET": "${{ secrets.SPOTIFY_CLIENT_SECRET }}", "SPOTIFY_REDIRECT_URI": "${{ secrets.SPOTIFY_REDIRECT_URI }}", "SPOTIFY_USERNAME": "${{ secrets.SPOTIFY_USERNAME }}"}'

  - uses: azure/webapps-deploy@v2
    with:
     app-name: ${{ env.AZURE_WEBAPP_NAME }}
     package: ${{ env.WORKING_DIRECTORY }}
     startup-command: ${{ env.STARTUP_COMMAND }}

     
  - name: logout
    run: |
     az logout